// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSWheatAdmin.DataBase.DbContexts;

namespace SSWheatAdmin.Migrations
{
    [DbContext(typeof(InvestmentFundDbContext))]
    [Migration("20220601191459_hh")]
    partial class hh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.AccountDTO", b =>
                {
                    b.Property<ushort>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AvailableCredit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerNationalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("OwnerNationalId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.LoanInstallmentsDTO", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("LoanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanInstallments");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.LoansDTO", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("InstallmentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LendDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccountNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.PeoplesDTO", b =>
                {
                    b.Property<string>("NationalId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccountNumber")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("NationalId");

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.TransactionsDTO", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("AccountId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccountNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.AccountDTO", b =>
                {
                    b.HasOne("SSWheatAdmin.DataBase.DTOs.PeoplesDTO", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerNationalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.LoanInstallmentsDTO", b =>
                {
                    b.HasOne("SSWheatAdmin.DataBase.DTOs.LoansDTO", "Loan")
                        .WithMany("Installments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.LoansDTO", b =>
                {
                    b.HasOne("SSWheatAdmin.DataBase.DTOs.AccountDTO", "Account")
                        .WithMany("Loans")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.TransactionsDTO", b =>
                {
                    b.HasOne("SSWheatAdmin.DataBase.DTOs.AccountDTO", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.AccountDTO", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.LoansDTO", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("SSWheatAdmin.DataBase.DTOs.PeoplesDTO", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
